# Generated by Django 6.0.7 on 2026-07-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(blank=True, default=0)),
                ("author", models.CharField(max_length=300)),
                ("pages", models.PositiveIntegerField(default=0)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_at", models.TimeField(auto_now_add=True)),
                ("updated_at", models.TimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
